services:
  cf_ddns_upnp:
    container_name: cf_ddns_upnp
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - TZ=America/New_York 
    volumes:
      - ./data:/app/data
    restart: unless-stopped